services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge
